In [2]:
import pandas as pd
import numpy as np
import pickle

In [3]:
df = pd.read_csv('iris.data')

In [33]:
df.head(50)

5.1  3.5  1.4  0.2      Iris-setosa
0   4.9  3.0  1.4  0.2      Iris-setosa
1   4.7  3.2  1.3  0.2      Iris-setosa
2   4.6  3.1  1.5  0.2      Iris-setosa
3   5.0  3.6  1.4  0.2      Iris-setosa
4   5.4  3.9  1.7  0.4      Iris-setosa
5   4.6  3.4  1.4  0.3      Iris-setosa
6   5.0  3.4  1.5  0.2      Iris-setosa
7   4.4  2.9  1.4  0.2      Iris-setosa
8   4.9  3.1  1.5  0.1      Iris-setosa
9   5.4  3.7  1.5  0.2      Iris-setosa
10  4.8  3.4  1.6  0.2      Iris-setosa
11  4.8  3.0  1.4  0.1      Iris-setosa
12  4.3  3.0  1.1  0.1      Iris-setosa
13  5.8  4.0  1.2  0.2      Iris-setosa
14  5.7  4.4  1.5  0.4      Iris-setosa
15  5.4  3.9  1.3  0.4      Iris-setosa
16  5.1  3.5  1.4  0.3      Iris-setosa
17  5.7  3.8  1.7  0.3      Iris-setosa
18  5.1  3.8  1.5  0.3      Iris-setosa
19  5.4  3.4  1.7  0.2      Iris-setosa
20  5.1  3.7  1.5  0.4      Iris-setosa
21  4.6  3.6  1.0  0.2      Iris-setosa
22  5.1  3.3  1.7  0.5      Iris-setosa
23  4.8  3.4  1.9  0.2      Iris-setosa
24  5.0  3.0  1.6  0.2      Iris-setosa
25  5.0  3.4  1.6  0.4      Iris-setosa
26  5.2  3.5  1.5  0.2      Iris-setosa
27  5.2  3.4  1.4  0.2      Iris-setosa
28  4.7  3.2  1.6  0.2      Iris-setosa
29  4.8  3.1  1.6  0.2      Iris-setosa
30  5.4  3.4  1.5  0.4      Iris-setosa
31  5.2  4.1  1.5  0.1      Iris-setosa
32  5.5  4.2  1.4  0.2      Iris-setosa
33  4.9  3.1  1.5  0.1      Iris-setosa
34  5.0  3.2  1.2  0.2      Iris-setosa
35  5.5  3.5  1.3  0.2      Iris-setosa
36  4.9  3.1  1.5  0.1      Iris-setosa
37  4.4  3.0  1.3  0.2      Iris-setosa
38  5.1  3.4  1.5  0.2      Iris-setosa
39  5.0  3.5  1.3  0.3      Iris-setosa
40  4.5  2.3  1.3  0.3      Iris-setosa
41  4.4  3.2  1.3  0.2      Iris-setosa
42  5.0  3.5  1.6  0.6      Iris-setosa
43  5.1  3.8  1.9  0.4      Iris-setosa
44  4.8  3.0  1.4  0.3      Iris-setosa
45  5.1  3.8  1.6  0.2      Iris-setosa
46  4.6  3.2  1.4  0.2      Iris-setosa
47  5.3  3.7  1.5  0.2      Iris-setosa
48  5.0  3.3  1.4  0.2      Iris-setosa
49  7.0  3.2  4.7  1.4  Iris-versicolor

In [7]:
df.shape

(149, 5)

In [10]:
X = np.array(df.iloc[:,0:4])
y = np.array(df.iloc[:,-1])

In [12]:
y

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       '

In [13]:
from sklearn.preprocessing import LabelEncoder

In [14]:
le = LabelEncoder()
y = le.fit_transform(y.reshape(-1))

In [15]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [18]:
from sklearn.svm import SVC

In [19]:
sv = SVC(kernel='linear')
sv.fit(X_train,y_train)

SVC(kernel='linear')

In [21]:
y_pred = sv.predict(X_test)

In [22]:
y_pred

array([2, 2, 1, 1, 0, 2, 2, 1, 2, 1, 0, 0, 1, 0, 0, 2, 2, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 2])

In [23]:
y_test

array([2, 2, 1, 1, 0, 2, 2, 1, 2, 1, 0, 0, 1, 0, 0, 2, 2, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 2])

In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score

In [28]:
cm = confusion_matrix(y_test, y_pred)

In [29]:
cm

array([[12,  0,  0],
       [ 0, 10,  0],
       [ 0,  0,  8]], dtype=int64)

In [30]:
ac  = accuracy_score(y_test, y_pred)
ac

1.0

In [31]:
pickle.dump(sv, open('iris.pkl', 'wb'))